version: '3.9'

services:
  samplewebapi:
    image: samplewebapi
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_HTTPS_PORT=443
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/fullchain.pem
      - ASPNETCORE_Kestrel__Certificates__Default__KeyPath=/https/privkey.pem
    ports:
      - "9000:8080"
      - "9001:8081"
    volumes:
      - /etc/letsencrypt/live/4135999-tb87762.hostman.dev/fullchain.pem:/https/fullchain.pem:ro
      - /etc/letsencrypt/live/4135999-tb87762.hostman.dev/privkey.pem:/https/privkey.pem:ro
  
  rabbitmq:
    image: masstransit/rabbitmq:latest
    container_name: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    restart: always
    ports:
      - "15672:15672"  # Management UI
      - "5672:5672"    # Messaging Port
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "-q", "ping" ]
      interval: 10s
      timeout: 10s
      retries: 5
