version: '3.9'

services:
  samplewebapi:
    image: samplewebapi
    build:
      context: .
      dockerfile: SampleWebApi/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    ports:
      - "8080:8080"
  
  rabbitmq:
    image: masstransit/rabbitmq:latest
    container_name: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    restart: always
    ports:
      - "15672:15672"  # Management UI
      - "5672:5672"    # Messaging Port
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "-q", "ping" ]
      interval: 10s
      timeout: 10s
      retries: 5
